baseURL = "https://watchdogs2.nickwasused.com"
title = "Watch Dogs 2 Wiki"
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   tag = "Watch Dogs 2"

[params]
  geekdocRepo = "https://github.com/Nickwasused/WatchDogs2Data"

  # We use Lozad for that
  geekdocImageLazyLoading = false

  [params.geekdocContentLicense]
    name = "Mozilla Public License 2.0"
    link = "https://raw.githubusercontent.com/Nickwasused/WatchDogs2Data/main/LICENSE"