name: PHP Lint check
on: [push, pull_request]
jobs:
  lint:
    name: PHP Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: PHP syntax checker 8.0
        uses: StephaneBour/actions-php-lint@8.0
